UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW UW 
DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW DW 
